version: '3.9'
networks:
  vendas-network:
    external: true

services:
  auth-api:
    container_name: auth-api
    build: './app/auth-api'
    restart: always
    networks:
      - vendas-network
    ports:
      - 8080:8080
    environment:
      PORT: 8080

  product-api:
    container_name: product-api
    build: './app/product-api'
    restart: always
    networks:
      - vendas-network
    ports:
      - 8081:8081
    environment:
      PORT: 8081

  sales-api:
    container_name: sales-api
    build: './app/sales-api'
    restart: always
    networks:
      - vendas-network
    ports:
      - 8082:8082
    environment:
      PORT: 8082
      
