server:
  port: ${PORT:8081}

spring:
  profiles:
    active: dev

---
spring:
  config:
    activate:
      on-profile: dev

  app:
    name: '<h1 style="color: black; font-size: 40px; font: cursive;">Utilizando o application.yaml, ambiente: development! </h1>'

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/product-db
    platform: postgresql
    username: "admin"
    password: 123456
    maxActive: 3

  jpa:
    hibernate:
      ddl-auto: create-drop
      format_sql: true
    open-in-view: false
---
spring:
  config:
    activate:
      on-profile: prod
  app:
    name: '<h1 style="color: black; font-size: 40px; font: cursive;">Utilizando o application.yaml, ambiente: production! </h1>'

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/product-db
    platform: postgresql
    username: "admin"
    password: 123456
    maxActive: 3

  jpa:
    hibernate:
      ddl-auto: none
      format_sql: true
    open-in-view: false
---
spring:
  config:
    activate:
      on-profile: hom
  app:
    name: '<h1 style="color: black; font-size: 40px; font: cursive;">Utilizando o application.yaml, ambiente: homologação! </h1>'

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/product-db
    platform: postgresql
    username: "admin"
    password: 123456
    maxActive: 3

  jpa:
    hibernate:
      ddl-auto: create-drop
      format_sql: true
    open-in-view: false
